# PyTorch Basic

PyTorch 기초 사용법

In [2]:
import numpy as np

import torch

In [3]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
nums.shape

torch.Size([9])

In [5]:
type(nums)

torch.Tensor

In [6]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [7]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
randoms = torch.rand((3,3))
randoms

tensor([[0.2982, 0.2272, 0.4167],
        [0.5309, 0.0015, 0.8090],
        [0.5410, 0.3576, 0.6113]])

In [9]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [13]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [14]:
nums  = nums.reshape((3,3))

In [15]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [16]:
result = torch.add(nums, 3)
result

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [17]:
result.numpy()

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

## View

In [18]:
range_nums = torch.arange(9).reshape(3,3)
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
# view는 reshape와 같은데 reshape을 권장
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index

In [21]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [22]:
nums[1]

tensor([3, 4, 5])

In [23]:
nums[1,1]

tensor(4)

In [24]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [25]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [26]:
arr = np.array([1,1,1])
arr

array([1, 1, 1])

In [27]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1], dtype=torch.int32)

In [28]:
arr_torch.float()

tensor([1., 1., 1.])

In [29]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [30]:
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

In [31]:
device

'cpu'

# AutoGrad
- 기울기를 주는 것

In [34]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [35]:
x2 = torch.ones(2,2)
x2

tensor([[1., 1.],
        [1., 1.]])

In [36]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [37]:
y2 = x2 + 2
y2

tensor([[3., 3.],
        [3., 3.]])

In [38]:
# grad_fn : x + 2를 계산한 값의 미분함수
print(y.grad_fn)

In [46]:
y.grad_fn

In [40]:
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [47]:
out =  z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [42]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [44]:
out.backward() # 모든 기울기를 알수있다.

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [72]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [73]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [74]:
# 기울기 안구함 > 따라서 속도가 더 빠름
with torch.no_grad():
    print((x ** 2).requires_grad)

False
